all: day1 day2 day4

day1:
	g++ --std=c++11 -Wall day1.cpp -o day1.exe

day2:
	g++ --std=c++11 -Wall day2.cpp -o day2.exe

day4:
	g++ --std=c++11 -Wall day4.cpp -o day4.exe

#hello.o: hello.c
#	 gcc -c hello.c
     
clean:
	rm day1.exe day2.exe day4.exe